package com.thakolkaran.model.entity;
// Generated Jun 11, 2018 2:12:53 PM by Hibernate Tools 5.2.3.Final


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name="cart"
    ,catalog="thakolkaran"
)
public class Cart  implements java.io.Serializable {


     private Integer id;
     private boolean isvalid;
     private String reason;
     private Date created;
     private Date updated;
     private Set<Usercartmapping> usercartmappings = new HashSet<Usercartmapping>(0);
     private Set<Payment> payments = new HashSet<Payment>(0);
     private Set<Cartornamentmapping> cartornamentmappings = new HashSet<Cartornamentmapping>(0);

    public Cart() {
    }

	
    public Cart(boolean isvalid, Date created, Date updated) {
        this.isvalid = isvalid;
        this.created = created;
        this.updated = updated;
    }
    public Cart(boolean isvalid, String reason, Date created, Date updated, Set<Usercartmapping> usercartmappings, Set<Payment> payments, Set<Cartornamentmapping> cartornamentmappings) {
       this.isvalid = isvalid;
       this.reason = reason;
       this.created = created;
       this.updated = updated;
       this.usercartmappings = usercartmappings;
       this.payments = payments;
       this.cartornamentmappings = cartornamentmappings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="isvalid", nullable=false)
    public boolean isIsvalid() {
        return this.isvalid;
    }
    
    public void setIsvalid(boolean isvalid) {
        this.isvalid = isvalid;
    }

    
    @Column(name="reason", length=40)
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=26)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=26)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cart")
    public Set<Usercartmapping> getUsercartmappings() {
        return this.usercartmappings;
    }
    
    public void setUsercartmappings(Set<Usercartmapping> usercartmappings) {
        this.usercartmappings = usercartmappings;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cart")
    public Set<Payment> getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set<Payment> payments) {
        this.payments = payments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cart")
    public Set<Cartornamentmapping> getCartornamentmappings() {
        return this.cartornamentmappings;
    }
    
    public void setCartornamentmappings(Set<Cartornamentmapping> cartornamentmappings) {
        this.cartornamentmappings = cartornamentmappings;
    }




}


