package com.thakolkaran.model.entity;
// Generated Jun 9, 2018 7:54:38 PM by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cartornamentmapping generated by hbm2java
 */
@Entity
@Table(name="cartornamentmapping"
    ,catalog="thakolkaran"
)
public class Cartornamentmapping  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private Ornament ornament;
     private Cart cart;
     private float goldcost;
     private float stonecost;
     private float tax;
     private int quantity;
     private boolean incart;
     private Date created;
     private Date updated;

    public Cartornamentmapping() {
    }

    public Cartornamentmapping(Category category, Ornament ornament, Cart cart, float goldcost, float stonecost, float tax, int quantity, boolean incart, Date created, Date updated) {
       this.category = category;
       this.ornament = ornament;
       this.cart = cart;
       this.goldcost = goldcost;
       this.stonecost = stonecost;
       this.tax = tax;
       this.quantity = quantity;
       this.incart = incart;
       this.created = created;
       this.updated = updated;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="categoryid", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ornamentid", nullable=false)
    public Ornament getOrnament() {
        return this.ornament;
    }
    
    public void setOrnament(Ornament ornament) {
        this.ornament = ornament;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cartid", nullable=false)
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }

    
    @Column(name="goldcost", nullable=false, precision=12, scale=0)
    public float getGoldcost() {
        return this.goldcost;
    }
    
    public void setGoldcost(float goldcost) {
        this.goldcost = goldcost;
    }

    
    @Column(name="stonecost", nullable=false, precision=12, scale=0)
    public float getStonecost() {
        return this.stonecost;
    }
    
    public void setStonecost(float stonecost) {
        this.stonecost = stonecost;
    }

    
    @Column(name="tax", nullable=false, precision=12, scale=0)
    public float getTax() {
        return this.tax;
    }
    
    public void setTax(float tax) {
        this.tax = tax;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="incart", nullable=false)
    public boolean isIncart() {
        return this.incart;
    }
    
    public void setIncart(boolean incart) {
        this.incart = incart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=26)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=26)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }




}


