package com.thakolkaran.model.entity;
// Generated Jun 9, 2018 7:54:38 PM by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Categoryornamentmapping generated by hbm2java
 */
@Entity
@Table(name="categoryornamentmapping"
    ,catalog="thakolkaran"
)
public class Categoryornamentmapping  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private Ornament ornament;
     private Date created;

    public Categoryornamentmapping() {
    }

    public Categoryornamentmapping(Category category, Ornament ornament, Date created) {
       this.category = category;
       this.ornament = ornament;
       this.created = created;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="categoryid", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ornamentid", nullable=false)
    public Ornament getOrnament() {
        return this.ornament;
    }
    
    public void setOrnament(Ornament ornament) {
        this.ornament = ornament;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=26)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }




}


