package com.thakolkaran.model.entity;
// Generated Jun 9, 2018 7:54:38 PM by Hibernate Tools 5.2.3.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="thakolkaran"
    , uniqueConstraints = {@UniqueConstraint(columnNames="name"), @UniqueConstraint(columnNames="order")} 
)
public class Category  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int order;
     private boolean isvisible;
     private Date created;
     private Date updated;
     private Set<Categoryornamentmapping> categoryornamentmappings = new HashSet<Categoryornamentmapping>(0);
     private Set<Cartornamentmapping> cartornamentmappings = new HashSet<Cartornamentmapping>(0);

    public Category() {
    }

	
    public Category(String name, int order, boolean isvisible, Date created, Date updated) {
        this.name = name;
        this.order = order;
        this.isvisible = isvisible;
        this.created = created;
        this.updated = updated;
    }
    public Category(String name, int order, boolean isvisible, Date created, Date updated, Set<Categoryornamentmapping> categoryornamentmappings, Set<Cartornamentmapping> cartornamentmappings) {
       this.name = name;
       this.order = order;
       this.isvisible = isvisible;
       this.created = created;
       this.updated = updated;
       this.categoryornamentmappings = categoryornamentmappings;
       this.cartornamentmappings = cartornamentmappings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="order", unique=true, nullable=false)
    public int getOrder() {
        return this.order;
    }
    
    public void setOrder(int order) {
        this.order = order;
    }

    
    @Column(name="isvisible", nullable=false)
    public boolean isIsvisible() {
        return this.isvisible;
    }
    
    public void setIsvisible(boolean isvisible) {
        this.isvisible = isvisible;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=26)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=26)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<Categoryornamentmapping> getCategoryornamentmappings() {
        return this.categoryornamentmappings;
    }
    
    public void setCategoryornamentmappings(Set<Categoryornamentmapping> categoryornamentmappings) {
        this.categoryornamentmappings = categoryornamentmappings;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<Cartornamentmapping> getCartornamentmappings() {
        return this.cartornamentmappings;
    }
    
    public void setCartornamentmappings(Set<Cartornamentmapping> cartornamentmappings) {
        this.cartornamentmappings = cartornamentmappings;
    }




}


