package com.thakolkaran.model.entity;
// Generated Jun 9, 2018 7:54:38 PM by Hibernate Tools 5.2.3.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Metal generated by hbm2java
 */
@Entity
@Table(name="metal"
    ,catalog="thakolkaran"
    , uniqueConstraints = @UniqueConstraint(columnNames="metal") 
)
public class Metal  implements java.io.Serializable {


     private Integer id;
     private String metal;
     private Boolean isvisible;
     private Date created;
     private Set<Ornament> ornaments = new HashSet<Ornament>(0);

    public Metal() {
    }

	
    public Metal(String metal, Date created) {
        this.metal = metal;
        this.created = created;
    }
    public Metal(String metal, Boolean isvisible, Date created, Set<Ornament> ornaments) {
       this.metal = metal;
       this.isvisible = isvisible;
       this.created = created;
       this.ornaments = ornaments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="metal", unique=true, nullable=false, length=45)
    public String getMetal() {
        return this.metal;
    }
    
    public void setMetal(String metal) {
        this.metal = metal;
    }

    
    @Column(name="isvisible")
    public Boolean getIsvisible() {
        return this.isvisible;
    }
    
    public void setIsvisible(Boolean isvisible) {
        this.isvisible = isvisible;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=26)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="metal")
    public Set<Ornament> getOrnaments() {
        return this.ornaments;
    }
    
    public void setOrnaments(Set<Ornament> ornaments) {
        this.ornaments = ornaments;
    }




}


