package com.thakolkaran.model.entity;
// Generated Jun 9, 2018 7:54:38 PM by Hibernate Tools 5.2.3.Final


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="payment"
    ,catalog="thakolkaran"
)
public class Payment  implements java.io.Serializable {


     private int id;
     private Cart cart;
     private String status;
     private float totalcost;
     private boolean proceedtopay;
     private Date created;
     private Date updated;

    public Payment() {
    }

    public Payment(int id, Cart usercart, String status, float totalcost, boolean proceedtopay, Date created, Date updated) {
       this.id = id;
       this.cart = usercart;
       this.status = status;
       this.totalcost = totalcost;
       this.proceedtopay = proceedtopay;
       this.created = created;
       this.updated = updated;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cartid", nullable=false)
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }

    
    @Column(name="status", nullable=false, length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="totalcost", nullable=false, precision=12, scale=0)
    public float getTotalcost() {
        return this.totalcost;
    }
    
    public void setTotalcost(float totalcost) {
        this.totalcost = totalcost;
    }

    
    @Column(name="proceedtopay", nullable=false)
    public boolean isProceedtopay() {
        return this.proceedtopay;
    }
    
    public void setProceedtopay(boolean proceedtopay) {
        this.proceedtopay = proceedtopay;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=26)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=26)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }




}


