package com.thakolkaran.model.entity;
// Generated Jun 21, 2018 3:14:05 PM by Hibernate Tools 5.2.3.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Season generated by hbm2java
 */
@Entity
@Table(name="season"
    ,catalog="thakolkaran"
)
public class Season  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String foldername;
     private String description;
     private Date startdate;
     private Date enddate;
     private Date created;
     private Date updated;
     private Set<Seasonwishmapping> seasonwishmappings = new HashSet<Seasonwishmapping>(0);

    public Season() {
    }

	
    public Season(String name, Date startdate, Date enddate, Date created, Date updated) {
        this.name = name;
        this.startdate = startdate;
        this.enddate = enddate;
        this.created = created;
        this.updated = updated;
    }
    public Season(String name, String description, Date startdate, Date enddate, Date created, Date updated, Set<Seasonwishmapping> seasonwishmappings) {
       this.name = name;
       this.description = description;
       this.startdate = startdate;
       this.enddate = enddate;
       this.created = created;
       this.updated = updated;
       this.seasonwishmappings = seasonwishmappings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="foldername", nullable=false, length=45)
   	public String getFoldername() {
   		return foldername;
   	}


   	public void setFoldername(String foldername) {
   		this.foldername = foldername;
   	}

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="startdate", nullable=false, length=26)
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="enddate", nullable=false, length=26)
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=26)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=26)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="season")
    public Set<Seasonwishmapping> getSeasonwishmappings() {
        return this.seasonwishmappings;
    }
    
    public void setSeasonwishmappings(Set<Seasonwishmapping> seasonwishmappings) {
        this.seasonwishmappings = seasonwishmappings;
    }



}


