package com.thakolkaran.model.entity;
// Generated Jun 21, 2018 3:14:05 PM by Hibernate Tools 5.2.3.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Seasonwishmapping generated by hbm2java
 */
@Entity
@Table(name="seasonwishmapping"
    ,catalog="thakolkaran"
)
public class Seasonwishmapping  implements java.io.Serializable {


     private Integer id;
     private Season season;
     private String message;
     private String imagename;
     private boolean isvisible;
     private Date created;

    public Seasonwishmapping() {
    }

	
    public Seasonwishmapping(Season season, String imagename, boolean isvisible, Date created) {
        this.season = season;
        this.imagename = imagename;
        this.isvisible = isvisible;
        this.created = created;
    }
    public Seasonwishmapping(Season season, String message, String imagename, boolean isvisible, Date created) {
       this.season = season;
       this.message = message;
       this.imagename = imagename;
       this.isvisible = isvisible;
       this.created = created;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="seasonid", nullable=false)
    public Season getSeason() {
        return this.season;
    }
    
    public void setSeason(Season season) {
        this.season = season;
    }

    
    @Column(name="message", length=100)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    
    @Column(name="imagename", nullable=false, length=50)
    public String getImagename() {
        return this.imagename;
    }
    
    public void setImagename(String imagename) {
        this.imagename = imagename;
    }

    
    @Column(name="isvisible", nullable=false)
    public boolean isIsvisible() {
        return this.isvisible;
    }
    
    public void setIsvisible(boolean isvisible) {
        this.isvisible = isvisible;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=26)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }




}


