package com.thakolkaran.model.entity;
// Generated Jun 9, 2018 7:54:38 PM by Hibernate Tools 5.2.3.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="thakolkaran"
)
public class User  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;
     private Date created;
     private Date updated;
     private Set<Usercartmapping> usercartmapping = new HashSet<Usercartmapping>(0);
     //private Set<Userdetails> userdetails = new HashSet<Userdetails>(0);
     private Userdetails userdetails;
     
    public User() {
    }

	
    public User(String username, String password, Date created, Date updated) {
        this.username = username;
        this.password = password;
        this.created = created;
        this.updated = updated;
    }
    public User(String username, String password, Date created, Date updated, Set<Usercartmapping> usercarts, Userdetails userdetailses) {
       this.username = username;
       this.password = password;
       this.created = created;
       this.updated = updated;
       this.usercartmapping = usercarts;
       this.setUserdetails(userdetailses);
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="username", nullable=false, length=50)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=90)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", nullable=false, length=26)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated", nullable=false, length=26)
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Usercartmapping> getUsercartmapping() {
        return this.usercartmapping;
    }
    
    public void setUsercartmapping(Set<Usercartmapping> usercartmapping) {
        this.usercartmapping = usercartmapping;
    }

 // @OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    @OneToOne (fetch=FetchType.LAZY,mappedBy="user")
	public Userdetails getUserdetails() {
		return userdetails;
	}


	public void setUserdetails(Userdetails userdetails) {
		this.userdetails = userdetails;
	}

    
	


	


    




}


